# Helm chart values
# image: 
#   repository: bitnamilegacy/redis
auth:
  enabled: false
global:
  storageClass: "longhorn"
master:
  persistence: 
    size: 1Gi
replica:
  persistence: 
    size: 1Gi 