# Helm chart values
image: 
  repository: bitnami/rabbitmq
  tag: latest
global:
  storageClass: "longhorn"
persistence:
  size: 1Gi
persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenScaled: Retain
  whenDeleted: Delete