# Helm chart values
image: 
  repository: bitnamilegacy/rabbitmq
global:
  storageClass: "longhorn"
persistence:
  size: 1Gi
persistentVolumeClaimRetentionPolicy:
  enabled: true
  whenScaled: Retain
  whenDeleted: Delete