cluster: 
  cluster:
    instances: 3
    postgresql:
      parameters:
        max_connections: "1000"
        wal_level: logical
        max_wal_senders: "20"
        max_replication_slots: "10"
      pg_hba: 
        - host all all 10.244.0.0/16 md5
      pg_ident: 
        - mymap   /^(.*)@mydomain\.com$      \1
    initdb: 
      database: registry
      owner: beckn
      secret:
        name: "postgresql" 
      postInitSQL:
        - CREATE DATABASE gateway WITH OWNER = beckn TEMPLATE = template0 ENCODING = 'UTF8' TABLESPACE = pg_default CONNECTION LIMIT = -1;
    monitoring:
      enabled: true
    storage:
      size: 1Gi
      storageClass: "longhorn"
    walStorage:
      enabled: false
      size: 1Gi
      storageClass: "longhorn"
